//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoCalculadora.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjetoCalculadora.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _25232 {
            get {
                object obj = ResourceManager.GetObject("25232", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2664 {
            get {
                object obj = ResourceManager.GetObject("2664", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _32176 {
            get {
                object obj = ResourceManager.GetObject("32176", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3740 {
            get {
                object obj = ResourceManager.GetObject("3740", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _43097 {
            get {
                object obj = ResourceManager.GetObject("43097", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _43743 {
            get {
                object obj = ResourceManager.GetObject("43743", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gratis_png_notacion_matematica_simbolo_matematico_subindice_y_superindice_signo_matematica {
            get {
                object obj = ResourceManager.GetObject("gratis-png-notacion-matematica-simbolo-matematico-subindice-y-superindice-signo-m" +
                        "atematica", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_basic_math_multiplication_sign_mathematics_clip_ar_through_the_cross_svg_png_icon_free_download_326_5b657234dc5860_9324711715333750289025 {
            get {
                object obj = ResourceManager.GetObject("kisspng-basic-math-multiplication-sign-mathematics-clip-ar-through-the-cross-svg-" +
                        "png-icon-free-download-326-5b657234dc5860.9324711715333750289025", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_multiplication_sign_clip_art_symbol_mathematics_wrong_svg_png_icon_free_download_4_424_onlin_5b92b5360134f5_025274501536341302005 {
            get {
                object obj = ResourceManager.GetObject("kisspng-multiplication-sign-clip-art-symbol-mathematics-wrong-svg-png-icon-free-d" +
                        "ownload-4-424-onlin-5b92b5360134f5.025274501536341302005", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_obelus_division_symbol_sign_computer_icons_divide_5ade4788561249_3837670715245167443526 {
            get {
                object obj = ResourceManager.GetObject("kisspng-obelus-division-symbol-sign-computer-icons-divide-5ade4788561249.38376707" +
                        "15245167443526", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_plus_and_minus_signs_computer_icons_plus_minus_sig_minus_5ae773a9e87774_5465678115251178659522 {
            get {
                object obj = ResourceManager.GetObject("kisspng-plus-and-minus-signs-computer-icons-plus-minus-sig-minus-5ae773a9e87774.5" +
                        "465678115251178659522", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_plus_and_minus_signs_meno_subtraction_mathematics_5b096e58c82dc1_54500362152734472882 {
            get {
                object obj = ResourceManager.GetObject("kisspng-plus-and-minus-signs-meno-subtraction-mathematics-5b096e58c82dc1.54500362" +
                        "152734472882", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kisspng_symbol_division_mathematics_obelus_computer_icons_divide_5ade47895fec22_4989581415245167453929 {
            get {
                object obj = ResourceManager.GetObject("kisspng-symbol-division-mathematics-obelus-computer-icons-divide-5ade47895fec22.4" +
                        "989581415245167453929", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap outrun_wallpaper__10__2017_01_25_0516 {
            get {
                object obj = ResourceManager.GetObject("outrun_wallpaper__10_-2017-01-25-0516", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_addition_plus_and_minus_signs_computer_icons_awesome_miscellaneous_cross_sign {
            get {
                object obj = ResourceManager.GetObject("png-transparent-addition-plus-and-minus-signs-computer-icons-awesome-miscellaneou" +
                        "s-cross-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_addition_plus_and_minus_signs_computer_icons_awesome_miscellaneous_cross_sign__1_ {
            get {
                object obj = ResourceManager.GetObject("png-transparent-addition-plus-and-minus-signs-computer-icons-awesome-miscellaneou" +
                        "s-cross-sign (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_line_font_minus_sign_line_minus_sign {
            get {
                object obj = ResourceManager.GetObject("png-transparent-line-font-minus-sign-line-minus-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_mathematical_notation_mathematics_symbol_subscript_and_superscript_sign_mathematics_angle_text_logo {
            get {
                object obj = ResourceManager.GetObject("png-transparent-mathematical-notation-mathematics-symbol-subscript-and-superscrip" +
                        "t-sign-mathematics-angle-text-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_obelus_division_symbol_mathematics_sign_dividing_line_miscellaneous_angle_text {
            get {
                object obj = ResourceManager.GetObject("png-transparent-obelus-division-symbol-mathematics-sign-dividing-line-miscellaneo" +
                        "us-angle-text", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_symbol_division_mathematics_obelus_computer_icons_divide_miscellaneous_black_sign {
            get {
                object obj = ResourceManager.GetObject("png-transparent-symbol-division-mathematics-obelus-computer-icons-divide-miscella" +
                        "neous-black-sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
